stages:
  - checkstyle
  - build
  - test

variables:
  DOCKER_HOST: "tcp://docker:2375"
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

checkstyle:tests:
  stage: checkstyle
  services:
    - name: docker:dind
  image: maven:3.8.1-openjdk-11
  script:
    - mvn checkstyle:check

build:tests:
  stage: build
  services:
    - name: docker:dind
  image: maven:3.8.1-openjdk-11
  script:
    - mvn clean verify -B -Dmaven.test.skip=true
  artifacts:
    expire_in: 24 hrs
    paths:
      - target/*


build:
  stage: build
  services:
    - name: docker:dind
  image: maven:3.8.1-openjdk-11
  script:
    - mvn $MAVEN_CLI_OPTS clean verify -B -Dmaven.test.skip=true
  artifacts:
    expire_in: 3 days



tests:
  stage: test
  services:
    - name: docker:dind
  image: maven:3.8.6-liberica-jdk-11
  script:
    - mvn $MAVEN_CLI_OPTS test -Dspring.profiles.active=test -Dmaven.test.skip=false


